<?xml version="1.0" encoding="utf-8"?><Database Name="Telephone" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=Telephone;User ID=sa" SettingsObjectName="THEME.Properties.Settings" SettingsPropertyName="TelephoneConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.infoation" Member="infoations">
    <Type Name="infoation">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TelephoneNO" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Addres" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Mode_of_connection" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="type_of_conntion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>